GT4SD/gt4sd-core

- src/gt4sd/frameworks/granular/train/__init__.py
- src/gt4sd/frameworks/granular/train/core.py
Add train granular
Signed-off-by: DIC <DIC@zurich.ibm.com>
> Add train granular

- setup.cfg
> chore: updated setup.cfg to include vcs requirements.

- .github/workflows/tests.yaml
- README.md
- setup.cfg
- src/gt4sd/cli/inference.py
- src/gt4sd/cli/trainer.py
Initial version of the inference client.
> GT4SD inference client

- .github/workflows/tests.yaml
- .gitignore
- README.md
- requirements.txt
- setup.cfg
- src/gt4sd/algorithms/controlled_sampling/advanced_manufacturing/core.py
- src/gt4sd/algorithms/controlled_sampling/advanced_manufacturing/implementation/nccr/core.py
- src/gt4sd/algorithms/controlled_sampling/paccmann_gp/core.py
- src/gt4sd/algorithms/core.py
- src/gt4sd/algorithms/generation/polymer_blocks/core.py
- src/gt4sd/algorithms/generation/polymer_blocks/implementation.py
- src/gt4sd/cli/algorithms.py
- src/gt4sd/cli/inference.py
- src/gt4sd/cli/saving.py
- src/gt4sd/cli/trainer.py
- src/gt4sd/domains/materials/__init__.py
- src/gt4sd/frameworks/granular/tokenizer/tokenizer.py
- src/gt4sd/training_pipelines/__init__.py
- src/gt4sd/training_pipelines/paccmann/core.py
- src/gt4sd/training_pipelines/paccmann/vae/core.py
- src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
- src/gt4sd/training_pipelines/tests/test_training_paccmann_vae.py
Initial definition of methods for configuration-training pipeline pairs.
> implementing model saving.

- src/gt4sd/configuration.py
Migrating COS remote to the new one.
> feat: migrating COS remote for default configuration.

- README.md
- requirements.txt
- setup.cfg
- src/gt4sd/algorithms/__init__.py
- src/gt4sd/algorithms/generation/moler/__init__.py
- src/gt4sd/algorithms/generation/moler/core.py
- src/gt4sd/algorithms/generation/moler/implementation.py
- src/gt4sd/algorithms/generation/tests/test_moler.py
- vcs_requirements.txt
Implementing MoLeR inference pipeline: https://github.com/microsoft/molecule-generation
> feat: implementing moler for inference.

- src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
- src/gt4sd/training_pipelines/tests/test_training_language_modeling.py
After discussing with @jannisborn, he pointed me to this  https://github.com/PyTorchLightning/pytorch-lightning/issues/11663.
Looking at the code-base I think these changes should address the segfault we were observing.
> feat: ensuring sentencepiece before pytorch_lightning.

- .github/workflows/pypi.yaml
- setup.cfg
- src/gt4sd/__init__.py
Fixing #72 
Bumping a patch version in order to publish a source distribution including package data.
> missing package_data in sdist, add wheel

- .github/workflows/cla-signature.yaml
> ci: fix CLA signature workflow

- CITATION.cff
- examples/README.md
- examples/protein_driven_molecule_generation/README.md
I set up an `examples` folder that can be expanded with other applications but for the moment it only contains an example of `PaccMannGP` with different target functions.
> Code example using PaccMannGP

- src/gt4sd/algorithms/controlled_sampling/paccmann_gp/implementation.py
- src/gt4sd/training_pipelines/regression_transformer/utils.py
> fix: handling target with deepcopy in PaccMannGP.

- src/gt4sd/algorithms/generation/moler/implementation.py
- vcs_requirements.txt
> refactor: reflect MoLeR update to 0.2.0

- src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py
- src/gt4sd/frameworks/torch/__init__.py
Ensuring that no device mismatches occur if RT inference is executed with CUDA availability
> fix: flexible device usage in RT inference

- src/gt4sd/configuration.py
Ensuring artifact management variables are customizable.
Testing custom variables I noticed that the dictionaries in the BaseSettings are immutable (they are using always the initial defaults).
See small example:
```console
(gt4sd-env) gt4sd@gt4sd-api-6db65dbbdb-lkvct:/usr/src/app$ env | grep -i bucket
GT4SD_S3_BUCKET_PROPERTIES=properties
GT4SD_S3_BUCKET_ALGORITHMS=algorithms
...
(gt4sd-env) gt4sd@gt4sd-api-6db65dbbdb-lkvct:/usr/src/app$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gt4sd.algorithms.registry import ApplicationsRegistry
...
>>> ApplicationsRegistry.list_available()
... …
```
> fix: configurable cache management.

- requirements.txt
- setup.cfg
- src/gt4sd/frameworks/enzeptional/optimization.py
- src/gt4sd/training_pipelines/pytorch_lightning/language_modeling/lm_datasets.py
- adding missing requirements (`loguru` and `joblib` are used inside the LM trainer)
- syncing requirements.txt and setup.cfg
> fix: missing deps in pip installation

- README.md
- conda_gpu.yml
- setup.cfg
* Adding new requirements for the pip package
> fix: add new requirements to pip package

- requirements.txt
- setup.cfg
- src/gt4sd/cli/trainer.py
- src/gt4sd/configuration.py
- src/gt4sd/frameworks/gflownet/arg_parser/parser.py
- src/gt4sd/frameworks/gflownet/tests/test_gfn.py
- src/gt4sd/frameworks/gflownet/train/core.py
- src/gt4sd/frameworks/granular/train/core.py
- src/gt4sd/training_pipelines/pytorch_lightning/core.py
- src/gt4sd/training_pipelines/pytorch_lightning/gflownet/core.py
- src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
- src/gt4sd/training_pipelines/tests/test_training_gflownet.py
* update trainers based on `lightning` to be compatible with `v1.7`
* add variable to handle `cudnn`
> update: pytorch_lightning and gpu training

- requirements.txt
- src/gt4sd/training_pipelines/tests/test_training_torchdrug_gcpn.py
- src/gt4sd/training_pipelines/tests/test_training_torchdrug_graphaf.py
We can support now also property optimization of the torchdrug molecules since they included some fixes in 0.2.0
Solves #58
> Torchdrug property optimization

- src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py
Minor PR. At inference time, a list of substructures could be provided to be excluded from the stochastic masking (`substructures_to_mask: List[str]`)
OLD: If a substructure could not be found in the seed SMILES (matching occurred on string level), it was ignored for all further steps.
NEW: The substructure is only ignored entirely if *additionally* it cannot be identified in the seed molecule with an RDKit substructure match. Instead, if this matching test is positive, the substructure will be ignored for the masking & generation part, but it will be used in the post-hoc filtering which essentially ensures that all returned molecules contain the substructure (note that this might slow down the inference time in edge cases)
> RT: Improved handling of substructures in generation task 

- conda_gpu.yml
- cpu_requirements.txt
- gpu_requirements.txt
- requirements.txt
- src/gt4sd/training_pipelines/regression_transformer/core.py
- src/gt4sd/training_pipelines/regression_transformer/utils.py
- vcs_requirements.txt
Minor improvements in RT training pipeline.
> chore: updating GPU build.

- src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py
Many RT models were trained on property values that were cast from the original range to a [0,1] range. Hence, the input and output property values, which should be in the original, user-understandable scale, have to be transformed before model execution.
Thus far, the only supported functions for (de)normalization was a linear transformation from the original scale to [0,1] and back.
This PR extends this functionality by allowing arbitrarily complex (de)normalization functions, in particular log-transformations. These functions are given as string lambda expressions in the model artifacts
> feat: support custom (de)normalization of property values in RT

- .github/workflows/tests.yaml
- CONTRIBUTING.md
- dev_requirements.txt
- pyproject.toml
- requirements.txt
- setup.cfg
- src/gt4sd/frameworks/gflownet/arg_parser/parser.py
- src/gt4sd/frameworks/gflownet/dataloader/data_module.py
- src/gt4sd/frameworks/gflownet/ml/module.py
- src/gt4sd/frameworks/gflownet/tests/test_gfn.py
- src/gt4sd/frameworks/gflownet/train/core.py
- src/gt4sd/frameworks/granular/arg_parser/parser.py
- src/gt4sd/frameworks/granular/dataloader/data_module.py
- src/gt4sd/frameworks/granular/ml/module.py
- src/gt4sd/frameworks/granular/train/core.py
- src/gt4sd/training_pipelines/__init__.py
- src/gt4sd/training_pipelines/pytorch_lightning/gflownet/core.py
- src/gt4sd/training_pipelines/pytorch_lightning/granular/core.py
- src/gt4sd/training_pipelines/pytorch_lightning/molformer/core.py
Upperbounding tensorflow-io-gcs-filesystem and importing before lightning to avoid segfaults.
> chore: ensuring order of tensorflow imports.

- requirements.txt
To keep package installation smooth and functional
> Upper bound requirements 
